manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: oORiggsOo
      url-base: https://github.com/oORiggsOo
    - name: MooseAntlers
      url-base: https://github.com/MooseAntlers
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: ec-support-zmk-module
      remote: MooseAntlers
      revision: main
    - name: MooseAntlers
      remote: MooseAntlers
      revision: main
  self:
    path: config
